### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by beeevita** [mingkaid/rl-prompt#21]
Hi, what is the specific version of transformers and torch? I have got the following error when running run_fsc.py:

Traceback (most recent call last):
  File "run_fsc.py", line 5, in <module>
    from rlprompt.models import (LMAdaptorModelConfig, SinglePromptModelConfig,
  File "/home/v-qingyanguo/code/rl-prompt/rlprompt/models/__init__.py", line 2, in <module>
    from .lm_adaptor_model import LMAdaptorModel
  File "/home/v-qingyanguo/code/rl-prompt/rlprompt/models/lm_adaptor_model.py", line 6, in <module>
    from transformers import pipeline, AutoTokenizer
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/transformers/__init__.py", line 3026, in __getattr__
    return super().__getattr__(name)
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/transformers/file_utils.py", line 1889, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/transformers/__init__.py", line 3020, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/anaconda/envs/rl_py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 30, in <module>
    from .automatic_speech_recognition import AutomaticSpeechRecognitionPipeline
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 20, in <module>
    from .base import Pipeline
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/transformers/pipelines/base.py", line 43, in <module>
    from ..models.auto.modeling_auto import AutoModel
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/transformers/models/auto/modeling_auto.py", line 109, in <module>
    from ..detr.modeling_detr import DetrForObjectDetection, DetrModel
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/transformers/models/detr/modeling_detr.py", line 44, in <module>
    from scipy.optimize import linear_sum_assignment
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/scipy/optimize/__init__.py", line 413, in <module>
    from ._linprog import linprog, linprog_verbose_callback
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/scipy/optimize/_linprog.py", line 21, in <module>
    from ._linprog_highs import _linprog_highs
  File "/anaconda/envs/rl_py38/lib/python3.8/site-packages/scipy/optimize/_linprog_highs.py", line 20, in <module>
    from ._highs._highs_wrapper import _highs_wrapper
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found

perhaps because of the version of transformers? Thanks for replying.

**Comment by mingkaid** [comment]
Hi there, I hope you've been able to solve the problem. Based on the error message, the problem is with `scipy`.

**Comment by beeevita** [comment]
Thanks. I have solved it. It's the problem of the path of the virtual environment.
